imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
framework:
    #esi:             ~
    translator:  { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         
        lifetime : 86400

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%" 

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [QuizmooUserBundle,QuizmooQuestionnaireBundle,FOSUserBundle,QuizmooRespondentBundle,StatisticBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            # tree:
            #     type: annotation
            #     alias: Gedmo
            #     prefix: Gedmo\Tree\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
services:
     my_user.facebook_provider:
        class: Quizmoo\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_provider.username_email"
            validator: "@validator"
            container: "@service_container"
     google.user:
         class: Quizmoo\UserBundle\Security\User\Provider\GoogleProvider
         arguments:
                 google: "@fos_google.api"
                 userManager: "@fos_user.user_provider.username_email"
                 validator: "@validator"
                 em: "@doctrine.orm.entity_manager"

# Swiftmailer Configuration
swiftmailer:
    #transport: "%mailer_transport%"
    #host:      "%mailer_host%"
    #username:  "%mailer_user%"
    #password:  "%mailer_password%"
    #spool:     { type: memory }
    transport: "smtp"
    host:      "smtp.quizmoo.com"
    username:  "noreply@quizmoo.com"
    password:  "abc123456"
    #port : 25
    #encryption: ssl
    #auth_mode:  login
fos_user:
    db_driver:    orm                             
    firewall_name: main                           
    user_class:    Quizmoo\UserBundle\Entity\User 
    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        form:
            type: quizmoo_user_registration
        confirmation:
            enabled:    true
            from_email:

                address:        noreply@quizmoo.com

                sender_name:    Bilel Abed Technical Test
    resetting:
        email:
            from_email:
                address:        noreply@quizmoo.com
                sender_name:    Technical Test
    profile:
        form:
            type: quizmoo_user_edit_profile

fos_facebook:
    alias:  facebook
    app_id: %api_facebook_id%
    secret: %api_facebook_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]
fos_google:
    app_name: disycs_quizmoo
    client_id: %client_id%
    client_secret: %client_secret%
    state: auth
    access_type: online
    scopes: [userinfo.email, userinfo.profile]
    approval_prompt: auto
    redirect_uri: %call_back_url%
parameters:
    max_questions_on_listepage: 8
    max_surveys_on_listepage: 6

