jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    #factories:
    #        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    encoders:
        Quizmoo\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                 providers: [in_memory, fos_userbundle,my_facebook_provider,google]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_facebook_provider:
            id: my_user.facebook_provider
        in_memory:
            memory:
                users:
                    foo: { password: test }
        google:
                 id: google.user
       

     

    firewalls:
         api_secured:
            pattern: /api/.*
            Api_Auth: true
            
         main:
            pattern:   ^/        
            form_login:
                provider:  fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: "%default_redirect_url%"
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            fos_facebook:
                default_target_path: "%default_redirect_url%"
                app_url: "%api_facebook_name%"
                server_url: "%api_facebook_server%"
                check_path: /login_facebook_check   
                provider: my_facebook_provider
            fos_google:
                default_target_path: "%default_redirect_url%"
                provider: google
                check_path: /login_google_check
            logout:
                path:       fos_user_security_logout
                target:     quizmoo_redirect_logout
            anonymous: true
            remember_me:
                key:        %secret% # %secret% est un parametre de parameters.yml

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/google/,           role: [ROLE_GOOGLE] }
        - { path: ^/surveys,role:ROLE_USER }

