parameters:
#    quizmoo_user.example.class: Quizmoo\UserBundle\Example

services:
    quizmoo.params:
        class: Quizmoo\UserBundle\Services\Params
        arguments: ['globals.yml']
#    quizmoo_user.example:
#        class: %quizmoo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    quizmoo.RessourceCheck_listener:
     class: Quizmoo\UserBundle\Listeners\RessourceCheckListener
     arguments: ['@service_container',@doctrine,@twig]
     tags:
             -  { name: kernel.event_listener, event: kernel.request, method: onRequest }
    apiauth.security.authentication.provider:
     class:  Quizmoo\UserBundle\firewall\token\ApiAuthProvider
     arguments: ['@doctrine']

    apiauth.security.authentication.listener:
     class:  Quizmoo\UserBundle\firewall\token\ApiTokenListener
     arguments: [@security.context, @security.authentication.manager]

    quizmoo_user_registration.form.type:
        class: Quizmoo\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name : form.type, alias: quizmoo_user_registration }

    quizmoo_user_edit_profile.edit.form.type:
        class: Quizmoo\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name : form.type, alias: quizmoo_user_edit_profile }