#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';
use  Quizmoo\QuestionnaireBundle\Command\GreetCommand;
use Quizmoo\QuestionnaireBundle\Command\CreateMTBQCommand;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Quizmoo\RespondentBundle\Command\CreateRankingAnswerCommand;
use Quizmoo\RespondentBundle\Command\CreateMatrixChoiceCommand;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->add(new GreetCommand());
$application->add(new CreateMTBQCommand());
$application->add(new CreateRankingAnswerCommand());
$application->add(new CreateMatrixChoiceCommand());
$application->run($input);
