<?php

namespace Quizmoo\QuestionnaireBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{


  public function getQuestions($questionnaireId)
  { 
    $qb = $this->_em->createQueryBuilder();
 
    $qb->select('q')
     ->from('QuizmooQuestionnaireBundle:Question', 'q')
     ->where('q.questionnaire = :id')
     ->setParameter('id', $questionnaireId);
 
    return $qb->getQuery()
              ->getResult();
  }

  public function countNbreOfQuestions($questionnaireId) {
   $qb = $this->_em->createQueryBuilder();
 
    $qb->select('count(q.id)')
     ->from('QuizmooQuestionnaireBundle:Question', 'q')
     ->where('q.questionnaire = :id')
     ->setParameter('id', $questionnaireId);
    try {
        return $qb->getQuery()
              ->getSingleScalarResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
  }

}
