<?php

namespace Quizmoo\QuestionnaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTypeRepository extends EntityRepository
{
	
	 public function getTypeByName($name)
	  {
	       
	        $qb = $this->createQueryBuilder('q')
	        ->where('q.questionTypeName = :name')
	        ->setParameter('name', $name);
	        return $qb->getQuery()
	                  ->getSingleResult();
	        
	  }
}
