<?php

namespace Quizmoo\QuestionnaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RankingQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingQuestionRepository extends EntityRepository
{
}
